---
title: "Train Delays in France - TidyTuesday 02-25-2019"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r load_libraries}
# devtools::install_github("thebioengineer/tidytuesdayR")
library(tidytuesdayR)
library(tidyverse)
library(gganimate)
library(rvest)
library(maps)

tt_data<-tt_load(2019,week=9)
tt_data
```

```{r helper functions}

# somewhat abusing how the wiki search functionality will send you directly to the wikipedia page
# if your search is specific enough
getCoords<-function(station,searchParams=""){
  print(paste("Accessing:", station))
  url<-paste0("https://en.wikipedia.org/w/index.php?search="
              ,gsub(" ","+",station),
              ifelse(searchParams=="","",
                     paste0("+",gsub(" ","+",searchParams))),
              "+railway+station")

  wiki_page<-xml2::read_html(url)
  coords<-wiki_page%>%
    rvest::html_node(".geo-dms")%>%
    rvest::html_text()
  
  if(is.na(coords)){
    url<-wiki_page%>%
      rvest::html_node(".mw-search-result-heading")%>%
      rvest::html_node("a")%>%
      rvest::html_attr("href")%>%
      paste0("https://en.wikipedia.org",.)
    
    wiki_page<-xml2::read_html(url)
    
    coords<-wiki_page%>%
      rvest::html_node(".geo-dms")%>%
      rvest::html_text()
  }
  
  coords<-clean_coords(strsplit(coords," ")[[1]])
  names(coords)<-c("long","lat")
  coords
}

# Coordinates recieved from wikipedia are in the "H M S"
clean_coords<-function(coord){
  coord_dec<-
    enc2native(coord)%>%
    gsub("<U+2033>","|",.,fixed = TRUE)%>%
    gsub("((\\d+)°)*((\\d+)')*((\\d+)|)*(.*)","\\2___\\4___\\6",.,perl = TRUE)%>%
    str_split("___")%>%
    purrr::map(as.numeric)%>%
    purrr::map(~sum(.x[1],.x[2]/60,.x[3]/3600,na.rm = TRUE))
  
  coord<-purrr::map2(coord_dec,coord,
                     function(.x,.y){
                       dirs<-data.frame(val=rep(1,length(.x)))
                       dirs$coord<-toupper(str_sub(.y,-1))
                       dirs$val[dirs$coord%in%c("S","W")]<--1
                       .x*dirs$val
                     })
  
  data.frame(coord)
}

```


```{r transform}


#which departure/arrival pairs have longest rides?
station_pairings<-tt_data$full_trains%>%
  group_by(departure_station,arrival_station)%>%
  summarise(mean_journey_time=sum(journey_time_avg*total_num_trips)/sum(total_num_trips))%>%
  ungroup%>%
  filter(mean_journey_time>quantile(.data$mean_journey_time,.80))%>%
  unite(routes,departure_station,arrival_station,sep = " -> ")%>%
  pull(routes)


Trains_delays<-tt_data$full_trains%>%
  unite(route,departure_station,arrival_station,sep = " -> ") %>% 
  select(year,month,service,route,total_num_trips,starts_with("num_greater"))%>%
  group_by(year,month,route)%>%
  summarize(totalTrips=sum(total_num_trips),
            late_15=sum(num_greater_15_min_late),
            late_30=sum(num_greater_30_min_late),
            late_60=sum(num_greater_60_min_late),
            perc_15_late=late_15/totalTrips*100,
            perc_30_late=late_30/totalTrips*100,
            perc_60_late=late_60/totalTrips*100)%>%
  arrange(route,year,month)%>%
  mutate(date=as.Date(paste(year,month,"1",sep = "-"),format="%Y-%m-%d"))%>%
  ungroup


# Get "directions" for train routes
train_station<-Trains_delays%>%
  select(route)%>%
  distinct%>%
  separate(route,c("origin","destination")," -> ")%>%
  unlist()%>%
  unique

train_station_coords<-data.frame(station=train_station)%>%
  mutate(searchParams=recode(station,
                     "BARCELONA"="Sants",
                     "BORDEAUX ST JEAN"="'Gare de Bordeaux' st-jean Station",
                     "PARIS VAUGIRARD"="(Paris Métro) Nord-Sud Company",
                     "ST PIERRE DES CORPS"="Gare Montparnasse",
                     .default = ""))%>%
  split(.$station)%>%
  purrr::map_df(~data.frame(station=.x$station,getCoords(.x$station,.$searchParams),
                            stringsAsFactors = FALSE))


Trains_delays_merged<-Trains_delays%>%
  separate(route,
           into = c("departure_station","arrival_station"),
           sep=" -> ",remove = FALSE)%>%
  rowwise()%>%
  mutate(departure_long=train_station_coords[train_station_coords$station==.data$departure_station,"long"],
         departure_lat=train_station_coords[train_station_coords$station==.data$departure_station,"lat"],
         arrival_long=train_station_coords[train_station_coords$station==.data$arrival_station,"long"],
         arrival_lat=train_station_coords[train_station_coords$station==.data$arrival_station,"lat"])%>%
  select(-departure_station,-arrival_station)%>%
  unite(dateTime,month,year,sep = "/")%>%
  as.data.frame()

# https://ggplot2.tidyverse.org/reference/geom_map.html



France<-map_data('france')
class(France)<-c("sf","data.frame")

EuropeMap <- borders("world",colour="grey", fill="white")


ggplot() + 
  EuropeMap +
  geom_segment(data=Trains_delays_merged%>%
                 filter(dateTime=="1/2015"),
               aes(x=departure_lat, xend=arrival_lat,
                   y=departure_long, yend=arrival_long,
                   color=late_15)) +
  coord_cartesian(ylim=c(47, 50), xlim=c(1.5, 4.5)) +
  # Here comes the gganimate code
  transition_states(dateTime,transition_length = 2,state_length = 1) +
  enter_recolor() + 
  exit_recolor() +
  ease_aes('sine-in-out') +
  labs(title = 'Date: {frame}')




```





