---
title: "Chicago Bird Collisions - TidyTuesday 05-01-2019"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r load_libraries}
library(tidyverse)
library(tidytuesdayR)
library(janitor)

# devtools::install_github("ropensci/plotly") #the dev 
library(plotly)
library(htmlwidgets)

tt<-tt_load("2019-05-28")
tt
```

```{r transform}


wine_trends<-tt$`winemag-data-130k-v2` %>% 
  
  select(country,points,title,variety) %>% 
  
  mutate(year = gsub("(.*)([12][90]\\d{2})(.*)","\\2",title),
         year = as.numeric(year,format="%Y")) %>% 
  
  filter(!is.na(year)) %>% 
  
  group_by(variety) %>% 

  filter(n()>5000) %>%  #keep only the most common wines
  
  filter(year < 2019, year > 1995) %>% 
  
  ungroup



#dichotomize ratio by GDP?
  
wine_trend_plot <- ggplot(wine_trends)+
  geom_point(aes(x=year,
                 y=points,
                 color = variety,
                 text=title))+
  geom_smooth(aes(x=year,
                 y=points,
                 color = variety))

ggtitle("Ratio of Mismanaged Plastic to Total Plastic by GDP in 2010")+
  ylab("Mismanaged/Total Plastic Waste Ratio")+
  xlab("Log 10 of Per Capita GDP ($)")+
  # geom_density(aes(x=ratio_plastic,fill=HighGDP))+
  scale_x_log10()+
  geom_rug()
  
gdp_ratio_plotly<-ggplotly(gdp_ratio)

gdp_ratio_plotly$sizingPolicy$padding <- "0"

saveWidget(gdp_ratio_plotly,
           "2019-05-21/Plastic_Ratio_vs_GDP.html",     
           selfcontained = FALSE,
           libdir = "lib",
           title = "atio of Mismanaged Plastic to Total Plastic by GDP in 2010 - TidyTuesday May 22, 2019")

ggsave("2019-05-21/Plastic_Ratio_vs_GDP.png",gdp_ratio)


```





