---
title: "Tues_data"
author: "Ellis Hughes"
date: "2/26/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(nflscrapR)

tt <- tt_load(2020, week = 6)
tt

```

```{r}


# Testing Theory
seahawks_2012_att <- tt$attendance %>% 
  filter(team == "Seattle") %>% 
  filter(year == 2012) %>% 
  mutate(week = as.character(week)) %>% 
  unite(team, team, team_name,sep = " ")


seahawks_2012_record <- tt$games %>% 
  filter(home_team == "Seattle Seahawks" | away_team == "Seattle Seahawks") %>% 
  filter(year == 2012 ) %>% 
  mutate(
    is_home = home_team == "Seattle Seahawks",
    result = case_when(
      winner == "Seattle Seahawks" ~ "Win",
      tie == "Seattle Seahawks" ~ "Tie",
      TRUE ~ "Loss"),
    opponent = case_when(
      is_home ~ away_team,
      TRUE ~ home_team
    )
  ) %>% 
  mutate(week == as.character("week")) %>% 
  select(year, week, is_home, result, opponent)

team_colors <- nflteams %>% 
  filter(team == "Seattle Seahawks")

seahawks_input_data <- seahawks_2012_att %>% 
  left_join(seahawks_2012_record, by = c( "year","week")) %>% 
  left_join(team_colors, by = "team") %>% 
  mutate(
    result_color =
      case_when(
        result == "Win" ~ primary,
        result == "Loss" ~ secondary,
        result == "Tie" ~ tertiary
      )
  ) %>% 
  mutate(week = factor(week, 1:17)) %>% 
  filter(!is.na(weekly_attendance)) %>% 
  mutate( 
    game = row_number(),
    lab = paste0("Game", game, "\n",
          weekly_attendance,"\n",
          ifelse(is_home,"vs ", "@ "),opponent))

seahawks_input_data %>% 
  ggplot() +
  geom_bar(aes(
    x = week,
    y = weekly_attendance,
    fill = I(result_color)
  ),stat = "identity") +
  geom_label(
    aes(
      x = week,
      y = max(weekly_attendance) + 4000,
      label = lab
      ),
    size = 2.5) +
  coord_polar() +
  theme_void() +
  ggtitle(paste(unique(seahawks_input_data$team),"-",unique(seahawks_input_data$year)))


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
